import { __ } from '@wordpress/i18n';

const variations = [
  {
    name: 'classic-list',
    title: __('Classic List', 'up2'),
    description: __('Image left, content right posts list.', 'up2'),
    icon: 'list-view',
    scope: ['block'],
    attributes: {
      layoutType: 'classic-list',
      perPage: 6,
      columns: 1,
      titleColor: '#111827',
      linkTitle: false,
      showImage: true,
      showDate: true,
      showExcerpt: true,
      showReadMore: true,
      dateFontSize: 14,
      excerptMaxChars: 40,
      readMoreBgColor: '#111827',
      readMoreFontSize: 14,
    },
    isActive: ['layoutType'],
  },
  {
    name: 'grid-cards',
    title: __('Grid Cards', 'up2'),
    description: __('Posts displayed as card grid.', 'up2'),
    icon: 'grid-view',
    scope: ['block'],
    attributes: {
      layoutType: 'grid-cards',
      perPage: 6,
      columns: 3,
      titleColor: '#111827',
      linkTitle: true,
      showImage: true,
      showDate: true,
      showExcerpt: true,
      showReadMore: true,
      dateFontSize: 13,
      excerptMaxChars: 55,
      readMoreBgColor: '#2563eb',
      readMoreFontSize: 14,
    },
    isActive: ['layoutType'],
  },
  {
    name: 'compact-list',
    title: __('Compact List', 'up2'),
    description: __('Smaller image and shorter excerpt list layout.', 'up2'),
    icon: 'editor-ul',
    scope: ['block'],
    attributes: {
      layoutType: 'compact-list',
      perPage: 8,
      columns: 1,
      titleColor: '#111827',
      linkTitle: true,
      showImage: true,
      showDate: true,
      showExcerpt: true,
      showReadMore: true,
      dateFontSize: 12,
      excerptMaxChars: 24,
      readMoreBgColor: '#111827',
      readMoreFontSize: 12,
    },
    isActive: ['layoutType'],
  },
  {
    name: 'minimal-feed',
    title: __('Minimal Feed', 'up2'),
    description: __('Minimal post feed without image and read more button.', 'up2'),
    icon: 'excerpt-view',
    scope: ['block'],
    attributes: {
      layoutType: 'minimal-feed',
      perPage: 10,
      columns: 1,
      titleColor: '#111827',
      linkTitle: true,
      showImage: false,
      showDate: true,
      showExcerpt: true,
      showReadMore: false,
      dateFontSize: 13,
      excerptMaxChars: 32,
      readMoreBgColor: '#111827',
      readMoreFontSize: 12,
    },
    isActive: ['layoutType'],
  },
];

export default variations;